version: '3'
services:
  web:
    container_name: xarch_app
    build: .
    ports: 
      - "1999:1999"
    restart: on-failure
    environment:
      USING_SECURE: false
      SERVER: 0.0.0.0
      PORT: 1999
      DB_DRIVER: MYSQL
      DB_USER: "root"
      DB_PASS: ""
      DB_SERVER: mysql
      DB_PORT: 3306
      DB_NAME: "xarch"
      DB_MAX_IDLE_CON: 10
      DB_MAX_OPEN_CON: 100
      DB_MAX_LIFE_TIME: 5
      RDB_ADDRESS: redis
      RDB_PORT: 6379
      RDB_USER: ""
      RDB_PASS: ""
      RDB_DB_DEFAULT: 0
      KAFKA_SERVER: kafka
      KAFKA_PORT: 29092
      KAFKA_CONSUMER_GROUP: "xarch"
      TOPIC_EMAIL_VERIFIED: "xarch.email_verif"
      TOPIC_PASS_FORGOT: "xarch.email_pass_forgot"
      ALQURAN_API: "https://quranlci.com/api/"
      JWT_SECRET_KEY: ""
      JWT_EXPIRED: 24  
      EMAIL_HOST: ""
      EMAIL_PORT: 465
      EMAIL_NAME: "XARCH"
      EMAIL_EMAIL: ""
      EMAIL_PASSWORD: ""
      CLOUD_NAME: ""
      API_KEY: ""
      API_SECRET: ""